apiVersion: v1
kind: Service
metadata:
  name: prac5p-service
spec:
  type: NodePort
  selector:
    app: prac5p
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
